-- DATA CONTINUITY CANDIDATE ONLY.
-- Promote this file with `supabase migration new provider_metric_snapshots` during an approved
-- production migration window. Do not apply directly from this docs path.

create table if not exists public.provider_metric_snapshots (
  id bigint generated by default as identity primary key,
  provider text not null,
  snapshot_date date not null,
  dataset text not null,
  chunk_index integer not null default 0,
  row_count integer not null default 0,
  payload jsonb not null default '{}'::jsonb,
  source_version text not null default 'v1',
  captured_at timestamptz not null default now(),

  constraint provider_metric_snapshots_provider_valid
    check (provider in ('gsc', 'ga4', 'posthog', 'meta')),
  constraint provider_metric_snapshots_dataset_valid
    check (dataset ~ '^[a-z0-9_]{1,80}$'),
  constraint provider_metric_snapshots_chunk_valid
    check (chunk_index between 0 and 500),
  constraint provider_metric_snapshots_row_count_valid
    check (row_count between 0 and 25000),
  constraint provider_metric_snapshots_payload_bound
    check (octet_length(payload::text) <= 2000000),
  constraint provider_metric_snapshots_unique_chunk
    unique (provider, snapshot_date, dataset, chunk_index)
);

create index if not exists idx_provider_metric_snapshots_lookup
  on public.provider_metric_snapshots (provider, snapshot_date desc, dataset, chunk_index);

alter table public.provider_metric_snapshots enable row level security;

revoke all on table public.provider_metric_snapshots from anon;
revoke insert, update, delete on table public.provider_metric_snapshots from authenticated;
grant select on table public.provider_metric_snapshots to authenticated;

drop policy if exists provider_metric_snapshots_admin_select on public.provider_metric_snapshots;
create policy provider_metric_snapshots_admin_select
  on public.provider_metric_snapshots
  for select
  to authenticated
  using ((select public.is_admin()));

comment on table public.provider_metric_snapshots is
  'Private daily aggregate/provider archive. Trusted server/Edge writers only; never store provider credentials or user-level PII.';
