import type { ClubDataPriorityRow, Metric, PostHogMetrics } from '@/lib/founder-analytics/types';

function MetricTile({ label, metric, value, suffix = '', detail, emptyLabel }: { label: string; metric?: Metric; value?: number; suffix?: string; detail: string; emptyLabel?: string }) {
  const delta = metric?.changePercent;
  return <article className="rounded-2xl border border-gray-200 bg-white p-5"><div className="flex justify-between gap-2"><p className="text-sm font-medium text-gray-500">{label}</p>{delta == null && metric ? <span className="text-xs font-bold text-blue-700">Yeni</span> : metric ? <span className={`text-xs font-bold ${delta! > 0 ? 'text-emerald-700' : delta! < 0 ? 'text-red-700' : 'text-gray-500'}`}>{delta! > 0 ? '↑ ' : delta! < 0 ? '↓ ' : ''}{Math.abs(delta!)}%</span> : null}</div><p className="mt-3 text-3xl font-bold">{emptyLabel ?? new Intl.NumberFormat('az-AZ', { maximumFractionDigits: 2 }).format(value ?? metric?.current ?? 0)}{emptyLabel ? '' : suffix}</p><p className="mt-2 text-xs text-gray-500">{detail}</p></article>;
}

function reachRate(value: number, base: number) { return base > 0 ? Math.round((value / base) * 10_000) / 100 : 0; }

function missingFieldLabel(field: ClubDataPriorityRow['missingFields'][number]) {
  return field === 'image' ? 'şəkil' : field === 'phone' ? 'telefon' : field === 'social' ? 'sosial profil' : field === 'coordinates' ? 'koordinat' : 'klub tipi';
}

function evidenceLabel(state: ClubDataPriorityRow['evidenceState']) {
  return state === 'fresh' ? 'Təzə sübut' : state === 'stale' ? 'Köhnə sübut' : 'Sübut yoxdur';
}

export function ExtendedAnalyticsSections({ posthog, clubDataPriorities }: { posthog: PostHogMetrics; clubDataPriorities: ClubDataPriorityRow[] }) {
  const funnel = posthog.funnel;
  const returnLoop = posthog.returnLoop;
  const supplyFunnel = posthog.supplyFunnel;
  const discoveryQuality = posthog.discoveryQuality;
  const webVitals = posthog.webVitals;
  const retentionRows = [
    ['D1', posthog.retention.d1, posthog.retention.d1CohortUsers],
    ['D3', posthog.retention.d3, posthog.retention.d3CohortUsers],
    ['D7', posthog.retention.d7, posthog.retention.d7CohortUsers],
  ] as const;
  const funnelRows = [
    ['Giriş sessiyası', funnel.landingSessions],
    ['Kart kliki və ya klub baxışı', funnel.discoverySessions],
    ['Klub profil baxışı', funnel.clubViewSessions],
    ['Əlaqə niyyəti', funnel.ctaSessions],
  ] as const;

  return <>
    <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Əlavə icraçı göstəricilər"><MetricTile label="Yeni istifadəçilər" value={posthog.newUsers} detail="Seçilmiş intervalda ilk dəfə görünən public istifadəçilər (365 günlük lookback daxilində)" /><MetricTile label="Geri qayıdan istifadəçilər" value={posthog.returningUsers} detail={`${posthog.returningRate}% geri qayıtma faizi`} /><MetricTile label="Sessiya / istifadəçi" value={posthog.sessionsPerUser} detail={`${posthog.usersWithThreeSessions} istifadəçi 3+ sessiya yaradıb`} /><MetricTile label="Telefon klikləri" metric={posthog.phoneClicks} detail="Telefon nömrəsi analitikaya göndərilmir" /><MetricTile label="Instagram klikləri" metric={posthog.instagramClicks} detail="Klub profilindən xarici keçid" /><MetricTile label="TikTok klikləri" metric={posthog.tiktokClicks} detail="Klub profilindən TikTok-a keçid" /><MetricTile label="İstiqamət klikləri" metric={posthog.mapsClicks} detail="Koordinatlar analitikaya göndərilmir" /><MetricTile label="Xəritədən istifadə" metric={posthog.mapUsage} detail="Xəritə mövqeyi və yaxınlıq sıralaması hadisələri" /><MetricTile label="Kart klikləri" metric={posthog.clubClicks} detail="Kəşf etmə hissəsindən klub seçimi" /><MetricTile label="Görünüş dəyişikliyi" metric={posthog.exploreViewChanges} detail="Siyahı/xəritə görünüş seçimi" /></section>

    <section className="mt-8 rounded-2xl border border-gray-200 bg-gray-50 p-6" aria-label="Geri dönüş modulu"><div><h2 className="text-xl font-bold">Geri dönüş modulu</h2><p className="mt-1 text-sm text-gray-500">Turnir/təklif modulu üçün real PostHog siqnalları. Sonrakı göstəricilər eyni sessiya və eyni klub üzrə çatımı göstərir; ardıcıl funnel kimi təqdim edilmir.</p></div><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricTile label="Yenilik göstərimləri" value={returnLoop.updateImpressions} detail={`${returnLoop.updateUsers} unikal istifadəçiyə çatıb`} /><MetricTile label="Ana səhifə → yenilik" value={returnLoop.updateDetailClicks} detail="Ana səhifə ön görünüşündən /yenilikler səhifəsinə keçid" /><MetricTile label="Yenilik sessiyaları" value={returnLoop.updateSessions} detail={`${returnLoop.returningUpdateUsers} geri qayıdan istifadəçi · ${returnLoop.returningUpdateRate}%`} /><MetricTile label="Kluba keçid" value={returnLoop.updateClubClicks} detail={`${returnLoop.downstreamClubViewSessions} sessiyada eyni klubun detail baxışı · ${returnLoop.clubViewReachRate}% çatım`} /><MetricTile label="Rəsmi mənbə klikləri" value={returnLoop.updateSourceClicks} detail="Təklif/turnir kartından verifikasiya mənbəsinə keçid" /><MetricTile label="Sonrakı əlaqə sessiyası" value={returnLoop.downstreamCtaSessions} detail={`${returnLoop.ctaReachRate}% yenilik sessiyası eyni klubda telefon/Instagram/Maps əlaqə niyyəti yaradıb`} /></div></section>

    <section className="mt-8 rounded-2xl border border-gray-200 bg-white p-6" aria-label="Klub sahibi müraciət axını"><div><h2 className="text-xl font-bold">Klub sahibi müraciət axını</h2><p className="mt-1 text-sm text-gray-500">Klub sahibi müraciət axınının real PostHog hadisələri. Müraciət sayı müştəri və ya ödəniş demək deyil.</p></div><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricTile label="Form baxışı" value={supplyFunnel.ownerClaimViews} detail={`${supplyFunnel.startRate}% forma başlama faizi`} /><MetricTile label="Formaya başlama" value={supplyFunnel.ownerClaimStarts} detail="İstifadəçi ilk real sahə ilə qarşılıqlı əlaqə yaradıb" /><MetricTile label="Göndərmə cəhdi" value={supplyFunnel.ownerClaimAttempts} detail={`${supplyFunnel.submitRate}% göndərmə uğur faizi`} /><MetricTile label="Göndərilən klub sahibi müraciəti" value={supplyFunnel.ownerClaimSent} detail={`${supplyFunnel.ownerClaimErrors} xəta · ${supplyFunnel.ownerClaimRateLimited} limitə düşən`} /><MetricTile label="Yeni klub siqnalı" value={supplyFunnel.newClubSent} detail={`${supplyFunnel.newClubViews} form baxışı · public təklif, təsdiqlənmiş klub deyil`} /><MetricTile label="Düzəliş siqnalı" value={supplyFunnel.correctionSent} detail={`${supplyFunnel.correctionViews} form baxışı · məlumat keyfiyyəti siqnalı`} /></div></section>

    <section className="mt-8 rounded-2xl border border-gray-200 bg-white p-6" aria-label="Real istifadəçi performansı"><div><h2 className="text-xl font-bold">Real istifadəçi performansı</h2><p className="mt-1 text-sm text-gray-500">PostHog performans hadisələrindən p75. Nümunə sayı həmişə birlikdə göstərilir; az nümunə stabil yaxşılaşma kimi şərh edilmir.</p></div><div className="mt-5 grid gap-4 sm:grid-cols-3"><MetricTile label="LCP p75" value={webVitals.lcpP75 ?? undefined} suffix=" ms" emptyLabel={webVitals.lcpP75 == null ? "—" : undefined} detail={`${webVitals.lcpSamples} nümunə`} /><MetricTile label="INP p75" value={webVitals.inpP75 ?? undefined} suffix=" ms" emptyLabel={webVitals.inpP75 == null ? "—" : undefined} detail={`${webVitals.inpSamples} nümunə`} /><MetricTile label="CLS p75" value={webVitals.clsP75 ?? undefined} emptyLabel={webVitals.clsP75 == null ? "—" : undefined} detail={`${webVitals.clsSamples} nümunə`} /></div></section>

    <section className="mt-8 rounded-2xl border border-gray-200 bg-white p-6" aria-label="PWA siqnalları"><div><h2 className="text-xl font-bold">PWA quraşdırma siqnalları</h2><p className="mt-1 text-sm text-gray-500">Quraşdırma imkanını, təsdiqlənmiş quraşdırmanı və standalone açılışı ayrı göstərir. “Quraşdırma imkanı” download deyil və eyni brauzerdə təkrarlana bilər.</p></div><div className="mt-5 grid gap-4 sm:grid-cols-3"><MetricTile label="Quraşdırma imkanı" value={posthog.pwa.installAvailable} detail="Quraşdırma imkanının göstərildiyi hadisə sayı" /><MetricTile label="Təsdiqlənmiş quraşdırma" value={posthog.pwa.installed} detail="Quraşdırmanın təsdiqləndiyi hadisə sayı" /><MetricTile label="Tətbiq rejimində açılış" value={posthog.pwa.standaloneOpened} detail="Quraşdırılmış tətbiq rejimində açılış" /></div></section>

    <section className="mt-8 rounded-2xl border border-gray-200 bg-white p-6" aria-label="Kəşf etmə keyfiyyəti"><div><h2 className="text-xl font-bold">Kəşf etmə keyfiyyəti</h2><p className="mt-1 text-sm text-gray-500">Axtarış və klub seçiminin sessiya-səviyyəli keyfiyyəti. Klub klik faizi görünən klub kartı sessiyalarından klik edilən sessiyalara nisbətdir.</p></div><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricTile label="Axtarış sessiyası" value={discoveryQuality.searchSessions} detail={`${discoveryQuality.zeroResultRate}% nəticəsiz axtarış faizi`} /><MetricTile label="Nəticəsiz axtarış" value={discoveryQuality.zeroResultSearchSessions} detail="Klub bazası, ad variantı və tapılma boşluğu üçün siqnal" /><MetricTile label="Filtrdən istifadə faizi" value={discoveryQuality.filterAdoptionRate} suffix="%" detail={`${discoveryQuality.filterSessions} filtr sessiyası / bütün kəşf sessiyaları; istifadəçi sayına bölünmür`} /><MetricTile label="Xəritədən istifadə faizi" value={discoveryQuality.mapAdoptionRate} suffix="%" detail={`${discoveryQuality.mapSessions} kəşf sessiyası xəritə/konum funksiyasından istifadə edib`} /><MetricTile label="Klub kartı görünən sessiya" value={discoveryQuality.clubImpressionSessions} detail="Ən azı bir klub kartı görünən sessiya" /><MetricTile label="Klub klik faizi" value={discoveryQuality.clubCtr} suffix="%" detail={`${discoveryQuality.clubClickSessions} sessiyada klub kartı seçilib`} /></div></section>

    <section className="mt-8 overflow-hidden rounded-2xl border border-gray-200 bg-white"><div className="border-b border-gray-100 p-6"><h2 className="text-xl font-bold">Trafik mənbələri</h2><p className="mt-1 text-sm text-gray-500">İlk giriş mənbə və kanal məlumatına əsaslanan normallaşdırılmış trafik mənbələri.</p></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr><th className="px-5 py-3">Kanal</th><th className="px-5 py-3">İstifadəçi</th><th className="px-5 py-3">Sessiya</th><th className="px-5 py-3">Klub profil sessiyası</th><th className="px-5 py-3">Əlaqə klikləri</th><th className="px-5 py-3">Əlaqə sessiyası</th><th className="px-5 py-3">Əlaqə faizi</th></tr></thead><tbody className="divide-y divide-gray-100">{posthog.acquisition.length === 0 ? <tr><td colSpan={7} className="px-5 py-8 text-gray-500">Trafik mənbə datası yoxdur.</td></tr> : posthog.acquisition.map((row) => <tr key={row.channel}><td className="px-5 py-3 font-semibold">{row.channel}</td><td className="px-5 py-3">{row.visitors}</td><td className="px-5 py-3">{row.sessions}</td><td className="px-5 py-3">{row.clubViewSessions}</td><td className="px-5 py-3">{row.ctaClicks}</td><td className="px-5 py-3 font-semibold">{row.ctaSessions}</td><td className="px-5 py-3 font-semibold">{row.ctaRate}%</td></tr>)}</tbody></table></div></section>

    <div className="mt-8 grid gap-6 xl:grid-cols-2"><section className="rounded-2xl border border-gray-200 bg-white p-6"><h2 className="text-xl font-bold">Mərhələ çatımı — ardıcıl axın deyil</h2><p className="mt-1 text-sm text-gray-500">Mərhələlər sessiya çatımı göstəriciləridir. Birbaşa Google/profil girişinə görə kart kliki məcburi əvvəlki addım deyil; itki kimi oxuma.</p>{!funnel.integrityOk ? <div className="mt-3 rounded-lg border border-red-200 bg-red-50 p-3 text-xs font-semibold text-red-800">Məlumat bütövlüyü xəbərdarlığı: əlaqə sessiyası klub profil sessiyasından çoxdur. Bu nəticələrlə dönüşüm qərarı vermə; analitika/build fərqini yoxla.</div> : <div className="mt-3 rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-xs font-semibold text-emerald-800">Çatım bütövlüyü yoxlaması keçib: əlaqə sessiyası klub profil sessiyasının alt qrupudur.</div>}<div className="mt-4 rounded-xl bg-violet-50 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-violet-700">Profil → əlaqə niyyəti</p><p className="mt-1 text-2xl font-bold">{funnel.profileToLeadRate}%</p><p className="mt-1 text-xs text-gray-500">Əlaqə niyyəti olan unikal sessiyalar / unikal klub profil sessiyaları. Bu rezervasiya və ya satış sübutu deyil.</p></div><div className="mt-5 space-y-3">{funnelRows.map(([label, value]) => <div key={label} className="rounded-xl bg-gray-50 p-4"><div className="flex items-center justify-between gap-4"><p className="text-sm font-semibold">{label}</p><p className="font-bold">{value}</p></div><p className="mt-1 text-xs text-gray-500">Giriş sessiyalarına nisbət: {reachRate(value, funnel.landingSessions)}%</p></div>)}</div></section><section className="rounded-2xl border border-gray-200 bg-white p-6"><h2 className="text-xl font-bold">Geri qayıtma</h2><p className="mt-1 text-sm text-gray-500">D1, D3 və D7 yalnız həmin gün pəncərəsi tamamlanmış istifadəçilər üzrə hesablanır; hər geri qayıtma göstəricisinin öz ölçülə bilən istifadəçi qrupu var. D30 bu paneldə hesablanmır.</p><div className="mt-5 grid grid-cols-2 gap-3"><MetricTile label="Geri qayıtma faizi" value={posthog.returningRate} suffix="%" detail="Cari intervalda aktiv olub intervaldan əvvəl də public sessiyası olan istifadəçilər" /><MetricTile label="Sessiya / istifadəçi" value={posthog.sessionsPerUser} detail="Cari interval ortalaması" />{retentionRows.map(([label, value, cohortUsers]) => <div key={label} className="rounded-xl bg-gray-50 p-4"><p className="text-xs text-gray-500">{label} retention</p><p className="mt-2 text-2xl font-bold">{value == null ? 'Yetərsiz data' : `${value}%`}</p><p className="mt-1 text-xs text-gray-500">Ölçülə bilən qrup: {cohortUsers} istifadəçi</p></div>)}</div><p className="mt-4 text-xs text-gray-500">Kampaniya cədvəlində Geri qayıdan sütunu cari intervaldan əvvəl də public sessiyası olan istifadəçiləri göstərir.</p></section></div>

    <section className="mt-8 overflow-hidden rounded-2xl border border-gray-200 bg-white"><div className="border-b border-gray-100 p-6"><h2 className="text-xl font-bold">Klub data prioritetləri</h2><p className="mt-1 text-sm text-gray-500">Profil boşluqları real demand ilə birləşdirilib. Yüksək prioritet daha çox baxış/CTA və daha böyük data boşluğu deməkdir.</p></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr><th className="px-5 py-3">Klub</th><th className="px-5 py-3">Prioritet</th><th className="px-5 py-3">Baxış</th><th className="px-5 py-3">CTA</th><th className="px-5 py-3">Tamlıq</th><th className="px-5 py-3">Çatmayan</th><th className="px-5 py-3">Sübut</th></tr></thead><tbody className="divide-y divide-gray-100">{clubDataPriorities.length === 0 ? <tr><td colSpan={7} className="px-5 py-8 text-gray-500">Prioritetləşdiriləcək data boşluğu yoxdur.</td></tr> : clubDataPriorities.slice(0, 10).map((club) => <tr key={club.slug}><td className="px-5 py-3"><p className="font-semibold">{club.name}</p><p className="text-xs text-gray-400">{club.slug}</p></td><td className="px-5 py-3 font-bold">{club.priorityScore}</td><td className="px-5 py-3">{club.views}</td><td className="px-5 py-3">{club.ctaClicks}</td><td className="px-5 py-3">{club.completenessScore}%</td><td className="px-5 py-3">{club.missingFields.length === 0 ? '—' : club.missingFields.map(missingFieldLabel).join(', ')}</td><td className="px-5 py-3">{evidenceLabel(club.evidenceState)}</td></tr>)}</tbody></table></div></section>

    <section className="mt-8 overflow-hidden rounded-2xl border border-gray-200 bg-white"><div className="border-b border-gray-100 p-6"><h2 className="text-xl font-bold">Kampaniya keyfiyyəti</h2><p className="mt-1 text-sm text-gray-500">Həcm, klub baxışı, geri dönüş və conversion birlikdə.</p></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr><th className="px-5 py-3">Kampaniya</th><th className="px-5 py-3">İstifadəçi</th><th className="px-5 py-3">Sessiya</th><th className="px-5 py-3">Geri qayıdan</th><th className="px-5 py-3">Sessiya/istifadəçi</th><th className="px-5 py-3">Klub profil sessiyası faizi</th><th className="px-5 py-3">Əlaqə sessiyası faizi</th></tr></thead><tbody className="divide-y divide-gray-100">{posthog.campaigns.map((row) => <tr key={`quality-${row.key}`}><td className="px-5 py-3"><p className="font-semibold">{row.campaign}</p><p className="text-xs text-gray-500">{row.source} · {row.medium}</p></td><td className="px-5 py-3">{row.visitors}</td><td className="px-5 py-3">{row.sessions}</td><td className="px-5 py-3">{row.returningUsers}</td><td className="px-5 py-3">{row.sessionsPerUser}</td><td className="px-5 py-3 font-semibold">{row.clubViewRate}%</td><td className="px-5 py-3 font-semibold">{row.conversionRate}%</td></tr>)}</tbody></table></div></section>
    <div className="mt-8 grid gap-6 xl:grid-cols-2"><section className="rounded-2xl border border-gray-200 bg-white p-6"><h2 className="text-xl font-bold">İzləmə tamlığı</h2><dl className="mt-4 divide-y divide-gray-100 text-sm"><div className="flex justify-between py-3"><dt className="text-gray-500">Mənbə məlumatı tamlığı</dt><dd className="font-bold">{posthog.tracking.attributionCompleteness}%</dd></div><div className="flex justify-between py-3"><dt className="text-gray-500">Source-u olmayan sessiya</dt><dd className="font-bold">{posthog.tracking.sourceMissingSessions}</dd></div><div className="flex justify-between py-3"><dt className="text-gray-500">Bot/avtomatlaşdırma hadisəsi</dt><dd className="font-bold">{posthog.tracking.botEvents}</dd></div></dl></section><section className="rounded-2xl border border-gray-200 bg-white p-6"><h2 className="text-xl font-bold">Davranış hadisələri</h2><dl className="mt-4 divide-y divide-gray-100 text-sm"><div className="flex justify-between py-3"><dt className="text-gray-500">Axtarış</dt><dd className="font-bold">{posthog.searchQueries.current}</dd></div><div className="flex justify-between py-3"><dt className="text-gray-500">Filtr dəyişiklikləri</dt><dd className="font-bold">{posthog.filterChanges.current}</dd></div><div className="flex justify-between py-3"><dt className="text-gray-500">Görünüş dəyişiklikləri</dt><dd className="font-bold">{posthog.exploreViewChanges.current}</dd></div><div className="flex justify-between py-3"><dt className="text-gray-500">Xəritə/konum istifadəsi</dt><dd className="font-bold">{posthog.mapUsage.current}</dd></div><div className="flex justify-between py-3"><dt className="text-gray-500">WhatsApp rezervasiya niyyəti</dt><dd className="font-bold">{posthog.whatsappBookingClicks.current}</dd></div></dl></section></div>

    <section className="mt-8 overflow-hidden rounded-2xl border border-gray-200 bg-white"><div className="border-b border-gray-100 p-6"><h2 className="text-xl font-bold">Klub çatımı və əlaqə niyyəti</h2><p className="mt-1 text-sm text-gray-500">Göstərimdən əlaqə niyyətinə qədər real hadisələr.</p></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr><th className="px-5 py-3">Klub / rayon</th><th className="px-5 py-3">Göstərim</th><th className="px-5 py-3">Kart kliki</th><th className="px-5 py-3">Profil baxışı</th><th className="px-5 py-3">Profil sessiyası</th><th className="px-5 py-3">Əlaqə klikləri</th><th className="px-5 py-3">Əlaqə sessiyası</th><th className="px-5 py-3">Profil→əlaqə</th></tr></thead><tbody className="divide-y divide-gray-100">{posthog.clubs.map((club) => { const totalCta = club.phoneClicks + club.instagramClicks + club.tiktokClicks + club.mapsClicks + club.whatsappBookingClicks; return <tr key={`reach-${club.slug}-${club.name}`}><td className="px-5 py-3"><p className="font-semibold">{club.name}</p><p className="text-xs text-gray-500">{club.district}</p></td><td className="px-5 py-3">{club.impressions}</td><td className="px-5 py-3">{club.cardClicks}</td><td className="px-5 py-3">{club.views}</td><td className="px-5 py-3">{club.viewSessions}</td><td className="px-5 py-3">{totalCta}</td><td className="px-5 py-3 font-semibold">{club.intentSessions}</td><td className="px-5 py-3 font-semibold">{club.intentRate}%</td></tr>; })}</tbody></table></div></section>
  </>;
}
