import type { ClubDataPriorityRow, Metric, PostHogMetrics } from '@/lib/founder-analytics/types';

function MetricTile({ label, metric, value, suffix = '', detail, emptyLabel }: { label: string; metric?: Metric; value?: number; suffix?: string; detail: string; emptyLabel?: string }) {
  const delta = metric?.changePercent;
  return <article className="rounded-2xl border border-gray-200 bg-white p-5"><div className="flex justify-between gap-2"><p className="text-sm font-medium text-gray-500">{label}</p>{delta == null && metric ? <span className="text-xs font-bold text-blue-700">Yeni</span> : metric ? <span className={`text-xs font-bold ${delta! > 0 ? 'text-emerald-700' : delta! < 0 ? 'text-red-700' : 'text-gray-500'}`}>{delta! > 0 ? '↑ ' : delta! < 0 ? '↓ ' : ''}{Math.abs(delta!)}%</span> : null}</div><p className="mt-3 text-3xl font-bold">{emptyLabel ?? new Intl.NumberFormat('az-AZ', { maximumFractionDigits: 2 }).format(value ?? metric?.current ?? 0)}{emptyLabel ? '' : suffix}</p><p className="mt-2 text-xs text-gray-500">{detail}</p></article>;
}

function reachRate(value: number, base: number) { return base > 0 ? Math.round((value / base) * 10_000) / 100 : 0; }

function missingFieldLabel(field: ClubDataPriorityRow['missingFields'][number]) {
  return field === 'image' ? 'şəkil' : field === 'phone' ? 'telefon' : field === 'instagram' ? 'Instagram' : field === 'coordinates' ? 'koordinat' : 'klub tipi';
}

function evidenceLabel(state: ClubDataPriorityRow['evidenceState']) {
  return state === 'fresh' ? 'Təzə sübut' : state === 'stale' ? 'Köhnə sübut' : 'Sübut yoxdur';
}

export function ExtendedAnalyticsSections({ posthog, clubDataPriorities }: { posthog: PostHogMetrics; clubDataPriorities: ClubDataPriorityRow[] }) {
  const funnel = posthog.funnel;
  const returnLoop = posthog.returnLoop;
  const supplyFunnel = posthog.supplyFunnel;
  const discoveryQuality = posthog.discoveryQuality;
  const webVitals = posthog.webVitals;
  const retentionRows = [
    ['D1', posthog.retention.d1, posthog.retention.d1CohortUsers],
    ['D3', posthog.retention.d3, posthog.retention.d3CohortUsers],
    ['D7', posthog.retention.d7, posthog.retention.d7CohortUsers],
  ] as const;
  const funnelRows = [
    ['Landing / session', funnel.landingSessions],
    ['Kart kliki və ya klub baxışı', funnel.discoverySessions],
    ['Klub detail baxışı', funnel.clubViewSessions],
    ['CTA', funnel.ctaSessions],
  ] as const;

  return <>
    <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Əlavə icraçı göstəricilər"><MetricTile label="Yeni istifadəçilər" value={posthog.newUsers} detail="Seçilmiş intervalda ilk dəfə görünən public istifadəçilər (365 günlük lookback daxilində)" /><MetricTile label="Returning users" value={posthog.returningUsers} detail={`${posthog.returningRate}% returning rate`} /><MetricTile label="Sessiya / istifadəçi" value={posthog.sessionsPerUser} detail={`${posthog.usersWithThreeSessions} istifadəçi 3+ sessiya yaradıb`} /><MetricTile label="Telefon klikləri" metric={posthog.phoneClicks} detail="Telefon nömrəsi analitikaya göndərilmir" /><MetricTile label="Instagram klikləri" metric={posthog.instagramClicks} detail="Klub profilindən xarici keçid" /><MetricTile label="İstiqamət klikləri" metric={posthog.mapsClicks} detail="Koordinatlar analitikaya göndərilmir" /><MetricTile label="Map usage" metric={posthog.mapUsage} detail="Map location və location sort eventləri" /><MetricTile label="Kart klikləri" metric={posthog.clubClicks} detail="Discovery-dən klub seçimi" /><MetricTile label="Görünüş dəyişikliyi" metric={posthog.exploreViewChanges} detail="List/map görünüş seçimi" /></section>

    <section className="mt-8 rounded-2xl border border-gray-200 bg-gray-50 p-6" aria-label="Return-loop reach"><div><h2 className="text-xl font-bold">Return-loop reach</h2><p className="mt-1 text-sm text-gray-500">Turnir/təklif modulu üçün real public PostHog siqnalları. Downstream göstəricilər eyni sessiya və eyni klub üzrə reach-dir; strict ordered funnel kimi təqdim edilmir.</p></div><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricTile label="Yenilik impressions" value={returnLoop.updateImpressions} detail={`${returnLoop.updateUsers} unikal istifadəçiyə çatıb`} /><MetricTile label="Ana səhifə → yenilik" value={returnLoop.updateDetailClicks} detail="Homepage preview-dən /yenilikler səhifəsinə keçid" /><MetricTile label="Yenilik sessiyaları" value={returnLoop.updateSessions} detail={`${returnLoop.returningUpdateUsers} returning istifadəçi · ${returnLoop.returningUpdateRate}%`} /><MetricTile label="Kluba keçid" value={returnLoop.updateClubClicks} detail={`${returnLoop.downstreamClubViewSessions} sessiyada eyni klubun detail baxışı · ${returnLoop.clubViewReachRate}% reach`} /><MetricTile label="Rəsmi mənbə klikləri" value={returnLoop.updateSourceClicks} detail="Təklif/turnir kartından verifikasiya mənbəsinə keçid" /><MetricTile label="Downstream CTA sessiyası" value={returnLoop.downstreamCtaSessions} detail={`${returnLoop.ctaReachRate}% yenilik sessiyası eyni klubda telefon/Instagram/Maps intent yaradıb`} /></div></section>

    <section className="mt-8 rounded-2xl border border-gray-200 bg-white p-6" aria-label="Owner claim funnel"><div><h2 className="text-xl font-bold">Klub sahibi funnel</h2><p className="mt-1 text-sm text-gray-500">Owner-claim axınının real PostHog eventləri. Müraciət sayı müştəri və ya ödəniş demək deyil.</p></div><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricTile label="Form baxışı" value={supplyFunnel.ownerClaimViews} detail={`${supplyFunnel.startRate}% form start rate`} /><MetricTile label="Form start" value={supplyFunnel.ownerClaimStarts} detail="İstifadəçi ilk real sahə ilə qarşılıqlı əlaqə yaradıb" /><MetricTile label="Submit cəhdi" value={supplyFunnel.ownerClaimAttempts} detail={`${supplyFunnel.submitRate}% submit success rate`} /><MetricTile label="Göndərilən owner claim" value={supplyFunnel.ownerClaimSent} detail={`${supplyFunnel.ownerClaimErrors} xəta · ${supplyFunnel.ownerClaimRateLimited} rate-limit`} /><MetricTile label="Yeni klub siqnalı" value={supplyFunnel.newClubSent} detail={`${supplyFunnel.newClubViews} form baxışı · public təklif, təsdiqlənmiş klub deyil`} /><MetricTile label="Düzəliş siqnalı" value={supplyFunnel.correctionSent} detail={`${supplyFunnel.correctionViews} form baxışı · data-quality input`} /></div></section>

    <section className="mt-8 rounded-2xl border border-gray-200 bg-white p-6" aria-label="Real user performance"><div><h2 className="text-xl font-bold">Real user performance</h2><p className="mt-1 text-sm text-gray-500">PostHog web_vital eventlərindən p75. Sample sayı həmişə birlikdə göstərilir; kiçik sample stabil yaxşılaşma kimi şərh edilmir.</p></div><div className="mt-5 grid gap-4 sm:grid-cols-3"><MetricTile label="LCP p75" value={webVitals.lcpP75 ?? undefined} suffix=" ms" emptyLabel={webVitals.lcpP75 == null ? "—" : undefined} detail={`${webVitals.lcpSamples} sample`} /><MetricTile label="INP p75" value={webVitals.inpP75 ?? undefined} suffix=" ms" emptyLabel={webVitals.inpP75 == null ? "—" : undefined} detail={`${webVitals.inpSamples} sample`} /><MetricTile label="CLS p75" value={webVitals.clsP75 ?? undefined} emptyLabel={webVitals.clsP75 == null ? "—" : undefined} detail={`${webVitals.clsSamples} sample`} /></div></section>

    <section className="mt-8 rounded-2xl border border-gray-200 bg-white p-6" aria-label="PWA siqnalları"><div><h2 className="text-xl font-bold">PWA install siqnalları</h2><p className="mt-1 text-sm text-gray-500">Quraşdırma imkanını, təsdiqlənmiş quraşdırmanı və standalone açılışı ayrı göstərir. “Quraşdırma imkanı” download deyil və eyni brauzerdə təkrarlana bilər.</p></div><div className="mt-5 grid gap-4 sm:grid-cols-3"><MetricTile label="Quraşdırma imkanı" value={posthog.pwa.installAvailable} detail="beforeinstallprompt event sayı" /><MetricTile label="Təsdiqlənmiş quraşdırma" value={posthog.pwa.installed} detail="appinstalled event sayı" /><MetricTile label="Standalone açılış" value={posthog.pwa.standaloneOpened} detail="Quraşdırılmış tətbiq rejimində açılış" /></div></section>

    <section className="mt-8 rounded-2xl border border-gray-200 bg-white p-6" aria-label="Discovery quality"><div><h2 className="text-xl font-bold">Discovery quality</h2><p className="mt-1 text-sm text-gray-500">Axtarış və klub seçiminin sessiya-səviyyəli keyfiyyəti. CTR görünən klub kartı sessiyalarından klub kartı klik sessiyalarına nisbətdir.</p></div><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricTile label="Axtarış sessiyası" value={discoveryQuality.searchSessions} detail={`${discoveryQuality.zeroResultRate}% zero-result rate`} /><MetricTile label="Nəticəsiz axtarış" value={discoveryQuality.zeroResultSearchSessions} detail="Inventory, alias və discoverability boşluğu üçün siqnal" /><MetricTile label="Filter adoption" value={discoveryQuality.filterAdoptionRate} suffix="%" detail={`${discoveryQuality.filterSessions} filter sessiyası / bütün discovery sessiyaları; user bazasına bölünmür`} /><MetricTile label="Map adoption" value={discoveryQuality.mapAdoptionRate} suffix="%" detail={`${discoveryQuality.mapSessions} discovery sessiyası map/location funksiyasından istifadə edib`} /><MetricTile label="Klub impression sessiyası" value={discoveryQuality.clubImpressionSessions} detail="Ən azı bir klub kartı görünən sessiya" /><MetricTile label="Klub CTR" value={discoveryQuality.clubCtr} suffix="%" detail={`${discoveryQuality.clubClickSessions} sessiyada klub kartı seçilib`} /></div></section>

    <section className="mt-8 overflow-hidden rounded-2xl border border-gray-200 bg-white"><div className="border-b border-gray-100 p-6"><h2 className="text-xl font-bold">Acquisition</h2><p className="mt-1 text-sm text-gray-500">First-touch source və medium əsasında normallaşdırılmış kanallar.</p></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr><th className="px-5 py-3">Kanal</th><th className="px-5 py-3">Users</th><th className="px-5 py-3">Sessions</th><th className="px-5 py-3">Club-view sess.</th><th className="px-5 py-3">CTA evt.</th><th className="px-5 py-3">Intent sess.</th><th className="px-5 py-3">Intent rate</th></tr></thead><tbody className="divide-y divide-gray-100">{posthog.acquisition.length === 0 ? <tr><td colSpan={7} className="px-5 py-8 text-gray-500">Acquisition datası yoxdur.</td></tr> : posthog.acquisition.map((row) => <tr key={row.channel}><td className="px-5 py-3 font-semibold">{row.channel}</td><td className="px-5 py-3">{row.visitors}</td><td className="px-5 py-3">{row.sessions}</td><td className="px-5 py-3">{row.clubViewSessions}</td><td className="px-5 py-3">{row.ctaClicks}</td><td className="px-5 py-3 font-semibold">{row.ctaSessions}</td><td className="px-5 py-3 font-semibold">{row.ctaRate}%</td></tr>)}</tbody></table></div></section>

    <div className="mt-8 grid gap-6 xl:grid-cols-2"><section className="rounded-2xl border border-gray-200 bg-white p-6"><h2 className="text-xl font-bold">Stage reach — strict funnel deyil</h2><p className="mt-1 text-sm text-gray-500">Mərhələlər sessiya reach göstəriciləridir. Birbaşa SEO/detail girişinə görə card click məcburi əvvəlki addım deyil; drop-off kimi oxuma.</p>{!funnel.integrityOk ? <div className="mt-3 rounded-lg border border-red-200 bg-red-50 p-3 text-xs font-semibold text-red-800">Data integrity warning: CTA sessiyası klub-detail sessiyasından çoxdur. Bu nəticələrlə conversion qərarı vermə; tracking/build fərqini yoxla.</div> : <div className="mt-3 rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-xs font-semibold text-emerald-800">Reach integrity check keçib: CTA sessiyası klub-detail sessiyasının subsetidir.</div>}<div className="mt-4 rounded-xl bg-violet-50 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-violet-700">Profile → lead</p><p className="mt-1 text-2xl font-bold">{funnel.profileToLeadRate}%</p><p className="mt-1 text-xs text-gray-500">Unikal outbound-lead sessiyaları / unikal klub-detail sessiyaları. Bu rezervasiya və ya satış sübutu deyil.</p></div><div className="mt-5 space-y-3">{funnelRows.map(([label, value]) => <div key={label} className="rounded-xl bg-gray-50 p-4"><div className="flex items-center justify-between gap-4"><p className="text-sm font-semibold">{label}</p><p className="font-bold">{value}</p></div><p className="mt-1 text-xs text-gray-500">Landing sessiyalarına nisbət: {reachRate(value, funnel.landingSessions)}%</p></div>)}</div></section><section className="rounded-2xl border border-gray-200 bg-white p-6"><h2 className="text-xl font-bold">Retention</h2><p className="mt-1 text-sm text-gray-500">D1, D3 və D7 yalnız həmin gün pəncərəsi tamamlanmış istifadəçilər üzrə hesablanır; hər retention göstəricisinin öz mature cohort denominatoru var. D30 bu dashboard-da hesablanmır.</p><div className="mt-5 grid grid-cols-2 gap-3"><MetricTile label="Returning rate" value={posthog.returningRate} suffix="%" detail="Cari intervalda aktiv olub intervaldan əvvəl də public sessiyası olan istifadəçilər" /><MetricTile label="Sessions / user" value={posthog.sessionsPerUser} detail="Cari interval ortalaması" />{retentionRows.map(([label, value, cohortUsers]) => <div key={label} className="rounded-xl bg-gray-50 p-4"><p className="text-xs text-gray-500">{label} retention</p><p className="mt-2 text-2xl font-bold">{value == null ? 'Yetərsiz data' : `${value}%`}</p><p className="mt-1 text-xs text-gray-500">Mature cohort: {cohortUsers} istifadəçi</p></div>)}</div><p className="mt-4 text-xs text-gray-500">Campaign cədvəlində Returning sütunu cari intervaldan əvvəl də public sessiyası olan istifadəçiləri göstərir.</p></section></div>

    <section className="mt-8 overflow-hidden rounded-2xl border border-gray-200 bg-white"><div className="border-b border-gray-100 p-6"><h2 className="text-xl font-bold">Klub data prioritetləri</h2><p className="mt-1 text-sm text-gray-500">Profil boşluqları real demand ilə birləşdirilib. Yüksək prioritet daha çox baxış/CTA və daha böyük data boşluğu deməkdir.</p></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr><th className="px-5 py-3">Klub</th><th className="px-5 py-3">Prioritet</th><th className="px-5 py-3">Baxış</th><th className="px-5 py-3">CTA</th><th className="px-5 py-3">Tamlıq</th><th className="px-5 py-3">Çatmayan</th><th className="px-5 py-3">Sübut</th></tr></thead><tbody className="divide-y divide-gray-100">{clubDataPriorities.length === 0 ? <tr><td colSpan={7} className="px-5 py-8 text-gray-500">Prioritetləşdiriləcək data boşluğu yoxdur.</td></tr> : clubDataPriorities.slice(0, 10).map((club) => <tr key={club.slug}><td className="px-5 py-3"><p className="font-semibold">{club.name}</p><p className="text-xs text-gray-400">{club.slug}</p></td><td className="px-5 py-3 font-bold">{club.priorityScore}</td><td className="px-5 py-3">{club.views}</td><td className="px-5 py-3">{club.ctaClicks}</td><td className="px-5 py-3">{club.completenessScore}%</td><td className="px-5 py-3">{club.missingFields.length === 0 ? '—' : club.missingFields.map(missingFieldLabel).join(', ')}</td><td className="px-5 py-3">{evidenceLabel(club.evidenceState)}</td></tr>)}</tbody></table></div></section>

    <section className="mt-8 overflow-hidden rounded-2xl border border-gray-200 bg-white"><div className="border-b border-gray-100 p-6"><h2 className="text-xl font-bold">Kampaniya keyfiyyəti</h2><p className="mt-1 text-sm text-gray-500">Həcm, klub baxışı, geri dönüş və conversion birlikdə.</p></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr><th className="px-5 py-3">Campaign</th><th className="px-5 py-3">Users</th><th className="px-5 py-3">Sessions</th><th className="px-5 py-3">Returning</th><th className="px-5 py-3">Sess/user</th><th className="px-5 py-3">Club-view sess. rate</th><th className="px-5 py-3">Intent sess. rate</th></tr></thead><tbody className="divide-y divide-gray-100">{posthog.campaigns.map((row) => <tr key={`quality-${row.key}`}><td className="px-5 py-3"><p className="font-semibold">{row.campaign}</p><p className="text-xs text-gray-500">{row.source} · {row.medium}</p></td><td className="px-5 py-3">{row.visitors}</td><td className="px-5 py-3">{row.sessions}</td><td className="px-5 py-3">{row.returningUsers}</td><td className="px-5 py-3">{row.sessionsPerUser}</td><td className="px-5 py-3 font-semibold">{row.clubViewRate}%</td><td className="px-5 py-3 font-semibold">{row.conversionRate}%</td></tr>)}</tbody></table></div></section>
    <div className="mt-8 grid gap-6 xl:grid-cols-2"><section className="rounded-2xl border border-gray-200 bg-white p-6"><h2 className="text-xl font-bold">Tracking completeness</h2><dl className="mt-4 divide-y divide-gray-100 text-sm"><div className="flex justify-between py-3"><dt className="text-gray-500">Attribution completeness</dt><dd className="font-bold">{posthog.tracking.attributionCompleteness}%</dd></div><div className="flex justify-between py-3"><dt className="text-gray-500">Source-u olmayan sessiya</dt><dd className="font-bold">{posthog.tracking.sourceMissingSessions}</dd></div><div className="flex justify-between py-3"><dt className="text-gray-500">Bot/automation event</dt><dd className="font-bold">{posthog.tracking.botEvents}</dd></div></dl></section><section className="rounded-2xl border border-gray-200 bg-white p-6"><h2 className="text-xl font-bold">Behavior events</h2><dl className="mt-4 divide-y divide-gray-100 text-sm"><div className="flex justify-between py-3"><dt className="text-gray-500">Search query</dt><dd className="font-bold">{posthog.searchQueries.current}</dd></div><div className="flex justify-between py-3"><dt className="text-gray-500">Filter changed</dt><dd className="font-bold">{posthog.filterChanges.current}</dd></div><div className="flex justify-between py-3"><dt className="text-gray-500">Explore view changed</dt><dd className="font-bold">{posthog.exploreViewChanges.current}</dd></div><div className="flex justify-between py-3"><dt className="text-gray-500">Map/location usage</dt><dd className="font-bold">{posthog.mapUsage.current}</dd></div></dl></section></div>

    <section className="mt-8 overflow-hidden rounded-2xl border border-gray-200 bg-white"><div className="border-b border-gray-100 p-6"><h2 className="text-xl font-bold">Klub reach və conversion</h2><p className="mt-1 text-sm text-gray-500">Impression-dan əlaqə niyyətinə qədər real eventlər.</p></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr><th className="px-5 py-3">Klub / rayon</th><th className="px-5 py-3">Impression</th><th className="px-5 py-3">Card click</th><th className="px-5 py-3">Detail evt.</th><th className="px-5 py-3">Detail sess.</th><th className="px-5 py-3">CTA evt.</th><th className="px-5 py-3">Intent sess.</th><th className="px-5 py-3">Detail→intent</th></tr></thead><tbody className="divide-y divide-gray-100">{posthog.clubs.map((club) => { const totalCta = club.phoneClicks + club.instagramClicks + club.mapsClicks; return <tr key={`reach-${club.slug}-${club.name}`}><td className="px-5 py-3"><p className="font-semibold">{club.name}</p><p className="text-xs text-gray-500">{club.district}</p></td><td className="px-5 py-3">{club.impressions}</td><td className="px-5 py-3">{club.cardClicks}</td><td className="px-5 py-3">{club.views}</td><td className="px-5 py-3">{club.viewSessions}</td><td className="px-5 py-3">{totalCta}</td><td className="px-5 py-3 font-semibold">{club.intentSessions}</td><td className="px-5 py-3 font-semibold">{club.intentRate}%</td></tr>; })}</tbody></table></div></section>
  </>;
}
