import type { Metric, PostHogMetrics } from '@/lib/founder-analytics/types';

function MetricTile({ label, metric, value, suffix = '', detail }: { label: string; metric?: Metric; value?: number; suffix?: string; detail: string }) {
  const delta = metric?.changePercent;
  return <article className="rounded-2xl border border-gray-200 bg-white p-5"><div className="flex justify-between gap-2"><p className="text-sm font-medium text-gray-500">{label}</p>{delta == null && metric ? <span className="text-xs font-bold text-blue-700">Yeni</span> : metric ? <span className={`text-xs font-bold ${delta! > 0 ? 'text-emerald-700' : delta! < 0 ? 'text-red-700' : 'text-gray-500'}`}>{delta! > 0 ? '↑ ' : delta! < 0 ? '↓ ' : ''}{Math.abs(delta!)}%</span> : null}</div><p className="mt-3 text-3xl font-bold">{new Intl.NumberFormat('az-AZ', { maximumFractionDigits: 2 }).format(value ?? metric?.current ?? 0)}{suffix}</p><p className="mt-2 text-xs text-gray-500">{detail}</p></article>;
}

function reachRate(value: number, base: number) { return base > 0 ? Math.round((value / base) * 10_000) / 100 : 0; }

export function ExtendedAnalyticsSections({ posthog }: { posthog: PostHogMetrics }) {
  const funnel = posthog.funnel;
  const returnLoop = posthog.returnLoop;
  const funnelRows = [
    ['Landing / session', funnel.landingSessions],
    ['Kart kliki və ya klub baxışı', funnel.discoverySessions],
    ['Klub detail baxışı', funnel.clubViewSessions],
    ['CTA', funnel.ctaSessions],
  ] as const;

  return <>
    <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Əlavə icraçı göstəricilər"><MetricTile label="Returning users" value={posthog.returningUsers} detail={`${posthog.returningRate}% returning rate`} /><MetricTile label="Sessiya / istifadəçi" value={posthog.sessionsPerUser} detail={`${posthog.usersWithThreeSessions} istifadəçi 3+ sessiya yaradıb`} /><MetricTile label="Telefon klikləri" metric={posthog.phoneClicks} detail="Telefon nömrəsi analitikaya göndərilmir" /><MetricTile label="Instagram klikləri" metric={posthog.instagramClicks} detail="Klub profilindən xarici keçid" /><MetricTile label="İstiqamət klikləri" metric={posthog.mapsClicks} detail="Koordinatlar analitikaya göndərilmir" /><MetricTile label="Map usage" metric={posthog.mapUsage} detail="Map location və location sort eventləri" /><MetricTile label="Kart klikləri" metric={posthog.clubClicks} detail="Discovery-dən klub seçimi" /><MetricTile label="Görünüş dəyişikliyi" metric={posthog.exploreViewChanges} detail="List/map görünüş seçimi" /></section>

    <section className="mt-8 rounded-2xl border border-gray-200 bg-gray-50 p-6" aria-label="Return-loop reach"><div><h2 className="text-xl font-bold">Return-loop reach</h2><p className="mt-1 text-sm text-gray-500">Turnir/təklif modulu üçün real public PostHog siqnalları. Downstream göstəricilər eyni sessiya və eyni klub üzrə reach-dir; strict ordered funnel kimi təqdim edilmir.</p></div><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricTile label="Yenilik impressions" value={returnLoop.updateImpressions} detail={`${returnLoop.updateUsers} unikal istifadəçiyə çatıb`} /><MetricTile label="Yenilik sessiyaları" value={returnLoop.updateSessions} detail={`${returnLoop.returningUpdateUsers} returning istifadəçi · ${returnLoop.returningUpdateRate}%`} /><MetricTile label="Kluba keçid" value={returnLoop.updateClubClicks} detail={`${returnLoop.downstreamClubViewSessions} sessiyada eyni klubun detail baxışı · ${returnLoop.clubViewReachRate}% reach`} /><MetricTile label="Rəsmi mənbə klikləri" value={returnLoop.updateSourceClicks} detail="Təklif/turnir kartından verifikasiya mənbəsinə keçid" /><MetricTile label="Downstream CTA sessiyası" value={returnLoop.downstreamCtaSessions} detail={`${returnLoop.ctaReachRate}% yenilik sessiyası eyni klubda telefon/Instagram/Maps intent yaradıb`} /></div></section>

    <section className="mt-8 overflow-hidden rounded-2xl border border-gray-200 bg-white"><div className="border-b border-gray-100 p-6"><h2 className="text-xl font-bold">Acquisition</h2><p className="mt-1 text-sm text-gray-500">First-touch source və medium əsasında normallaşdırılmış kanallar.</p></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr><th className="px-5 py-3">Kanal</th><th className="px-5 py-3">Users</th><th className="px-5 py-3">Sessions</th><th className="px-5 py-3">Club views</th><th className="px-5 py-3">CTA</th><th className="px-5 py-3">CTA rate</th></tr></thead><tbody className="divide-y divide-gray-100">{posthog.acquisition.length === 0 ? <tr><td colSpan={6} className="px-5 py-8 text-gray-500">Acquisition datası yoxdur.</td></tr> : posthog.acquisition.map((row) => <tr key={row.channel}><td className="px-5 py-3 font-semibold">{row.channel}</td><td className="px-5 py-3">{row.visitors}</td><td className="px-5 py-3">{row.sessions}</td><td className="px-5 py-3">{row.clubViews}</td><td className="px-5 py-3">{row.ctaClicks}</td><td className="px-5 py-3 font-semibold">{row.ctaRate}%</td></tr>)}</tbody></table></div></section>

    <div className="mt-8 grid gap-6 xl:grid-cols-2"><section className="rounded-2xl border border-gray-200 bg-white p-6"><h2 className="text-xl font-bold">Stage reach</h2><p className="mt-1 text-sm text-gray-500">Mərhələlər müstəqil sessiya reach göstəriciləridir; ardıcıllıq və mərhələ itkisi hesablanmır.</p><div className="mt-5 space-y-3">{funnelRows.map(([label, value], index) => <div key={label} className="rounded-xl bg-gray-50 p-4"><div className="flex items-center justify-between gap-4"><p className="text-sm font-semibold">{index + 1}. {label}</p><p className="font-bold">{value}</p></div><p className="mt-1 text-xs text-gray-500">Landing sessiyalarına nisbət: {reachRate(value, funnel.landingSessions)}%</p></div>)}</div></section><section className="rounded-2xl border border-gray-200 bg-white p-6"><h2 className="text-xl font-bold">Retention</h2><p className="mt-1 text-sm text-gray-500">D1/D3/D7 yalnız yeddi günlük müşahidə pəncərəsi tamamlanan kohortda göstərilir.</p><div className="mt-5 grid grid-cols-2 gap-3"><MetricTile label="Returning rate" value={posthog.returningRate} suffix="%" detail="Cari intervalda aktiv olub intervaldan əvvəl də public sessiyası olan istifadəçilər" /><MetricTile label="Sessions / user" value={posthog.sessionsPerUser} detail="Cari interval ortalaması" />{([['D1', posthog.retention.d1], ['D3', posthog.retention.d3], ['D7', posthog.retention.d7]] as const).map(([label, value]) => <div key={label} className="rounded-xl bg-gray-50 p-4"><p className="text-xs text-gray-500">{label} retention</p><p className="mt-2 text-2xl font-bold">{value == null ? 'Yetərsiz data' : `${value}%`}</p></div>)}</div><p className="mt-4 text-xs text-gray-500">Uyğun kohort: {posthog.retention.cohortUsers} user. Campaign cədvəlində Returning sütunu cari intervaldan əvvəl də public sessiyası olan istifadəçiləri göstərir.</p></section></div>

    <section className="mt-8 overflow-hidden rounded-2xl border border-gray-200 bg-white"><div className="border-b border-gray-100 p-6"><h2 className="text-xl font-bold">Kampaniya keyfiyyəti</h2><p className="mt-1 text-sm text-gray-500">Həcm, klub baxışı, geri dönüş və conversion birlikdə.</p></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr><th className="px-5 py-3">Campaign</th><th className="px-5 py-3">Users</th><th className="px-5 py-3">Sessions</th><th className="px-5 py-3">Returning</th><th className="px-5 py-3">Sess/user</th><th className="px-5 py-3">Club-view rate</th><th className="px-5 py-3">CTA rate</th></tr></thead><tbody className="divide-y divide-gray-100">{posthog.campaigns.map((row) => <tr key={`quality-${row.key}`}><td className="px-5 py-3"><p className="font-semibold">{row.campaign}</p><p className="text-xs text-gray-500">{row.source} · {row.medium}</p></td><td className="px-5 py-3">{row.visitors}</td><td className="px-5 py-3">{row.sessions}</td><td className="px-5 py-3">{row.returningUsers}</td><td className="px-5 py-3">{row.sessionsPerUser}</td><td className="px-5 py-3 font-semibold">{row.clubViewRate}%</td><td className="px-5 py-3 font-semibold">{row.conversionRate}%</td></tr>)}</tbody></table></div></section>
    <div className="mt-8 grid gap-6 xl:grid-cols-2"><section className="rounded-2xl border border-gray-200 bg-white p-6"><h2 className="text-xl font-bold">Tracking completeness</h2><dl className="mt-4 divide-y divide-gray-100 text-sm"><div className="flex justify-between py-3"><dt className="text-gray-500">Attribution completeness</dt><dd className="font-bold">{posthog.tracking.attributionCompleteness}%</dd></div><div className="flex justify-between py-3"><dt className="text-gray-500">Source-u olmayan sessiya</dt><dd className="font-bold">{posthog.tracking.sourceMissingSessions}</dd></div><div className="flex justify-between py-3"><dt className="text-gray-500">Bot/automation event</dt><dd className="font-bold">{posthog.tracking.botEvents}</dd></div></dl></section><section className="rounded-2xl border border-gray-200 bg-white p-6"><h2 className="text-xl font-bold">Behavior events</h2><dl className="mt-4 divide-y divide-gray-100 text-sm"><div className="flex justify-between py-3"><dt className="text-gray-500">Search query</dt><dd className="font-bold">{posthog.searchQueries.current}</dd></div><div className="flex justify-between py-3"><dt className="text-gray-500">Filter changed</dt><dd className="font-bold">{posthog.filterChanges.current}</dd></div><div className="flex justify-between py-3"><dt className="text-gray-500">Explore view changed</dt><dd className="font-bold">{posthog.exploreViewChanges.current}</dd></div><div className="flex justify-between py-3"><dt className="text-gray-500">Map/location usage</dt><dd className="font-bold">{posthog.mapUsage.current}</dd></div></dl></section></div>

    <section className="mt-8 overflow-hidden rounded-2xl border border-gray-200 bg-white"><div className="border-b border-gray-100 p-6"><h2 className="text-xl font-bold">Klub reach və conversion</h2><p className="mt-1 text-sm text-gray-500">Impression-dan əlaqə niyyətinə qədər real eventlər.</p></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr><th className="px-5 py-3">Klub / rayon</th><th className="px-5 py-3">Impression</th><th className="px-5 py-3">Card click</th><th className="px-5 py-3">Detail</th><th className="px-5 py-3">CTA</th><th className="px-5 py-3">Detail→CTA</th></tr></thead><tbody className="divide-y divide-gray-100">{posthog.clubs.map((club) => { const totalCta = club.phoneClicks + club.instagramClicks + club.mapsClicks; return <tr key={`reach-${club.slug}-${club.name}`}><td className="px-5 py-3"><p className="font-semibold">{club.name}</p><p className="text-xs text-gray-500">{club.district}</p></td><td className="px-5 py-3">{club.impressions}</td><td className="px-5 py-3">{club.cardClicks}</td><td className="px-5 py-3">{club.views}</td><td className="px-5 py-3">{totalCta}</td><td className="px-5 py-3 font-semibold">{club.intentRate}%</td></tr>; })}</tbody></table></div></section>
  </>;
}
