create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  session_id text not null,
  path text not null,
  event_type text not null,
  club_slug text,
  created_at timestamptz not null default now(),
  constraint analytics_events_session_id_length check (char_length(session_id) between 8 and 64),
  constraint analytics_events_path_valid check (char_length(path) between 1 and 300 and path like '/%' and path not like '/admin%' and path not like '/api%'),
  constraint analytics_events_type_valid check (event_type in ('maps_click', 'phone_click', 'instagram_click')),
  constraint analytics_events_club_slug_valid check (club_slug is null or club_slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

create index if not exists idx_analytics_events_created_at on public.analytics_events (created_at desc);
create index if not exists idx_analytics_events_type_created_at on public.analytics_events (event_type, created_at desc);
create index if not exists idx_analytics_events_club_created_at on public.analytics_events (club_slug, created_at desc);

alter table public.analytics_events enable row level security;

revoke all on table public.analytics_events from anon, authenticated;
grant insert on table public.analytics_events to anon, authenticated;
grant select, delete on table public.analytics_events to authenticated;
grant usage, select on sequence public.analytics_events_id_seq to anon, authenticated;

drop policy if exists anon_insert_analytics_events on public.analytics_events;
create policy anon_insert_analytics_events on public.analytics_events
  for insert to anon
  with check (
    char_length(session_id) between 8 and 64
    and char_length(path) between 1 and 300
    and path like '/%'
    and path not like '/admin%'
    and path not like '/api%'
    and event_type in ('maps_click', 'phone_click', 'instagram_click')
    and (club_slug is null or club_slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
  );

drop policy if exists authenticated_insert_analytics_events on public.analytics_events;
create policy authenticated_insert_analytics_events on public.analytics_events
  for insert to authenticated
  with check (
    char_length(session_id) between 8 and 64
    and char_length(path) between 1 and 300
    and path like '/%'
    and path not like '/admin%'
    and path not like '/api%'
    and event_type in ('maps_click', 'phone_click', 'instagram_click')
    and (club_slug is null or club_slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
  );

drop policy if exists admin_read_analytics_events on public.analytics_events;
create policy admin_read_analytics_events on public.analytics_events
  for select to authenticated
  using (public.is_admin());

drop policy if exists admin_delete_analytics_events on public.analytics_events;
create policy admin_delete_analytics_events on public.analytics_events
  for delete to authenticated
  using (public.is_admin());

create or replace function public.get_admin_analytics()
returns jsonb
language sql
security invoker
set search_path = public, pg_temp
as $$
  select case
    when public.is_admin() then jsonb_build_object(
      'today_views', (select count(*) from public.page_views where created_at >= date_trunc('day', now() at time zone 'Asia/Baku') at time zone 'Asia/Baku'),
      'today_visitors', (select count(distinct session_id) from public.page_views where created_at >= date_trunc('day', now() at time zone 'Asia/Baku') at time zone 'Asia/Baku'),
      'views_7d', (select count(*) from public.page_views where created_at >= now() - interval '7 days'),
      'visitors_7d', (select count(distinct session_id) from public.page_views where created_at >= now() - interval '7 days'),
      'views_30d', (select count(*) from public.page_views where created_at >= now() - interval '30 days'),
      'visitors_30d', (select count(distinct session_id) from public.page_views where created_at >= now() - interval '30 days'),
      'cta_30d', coalesce((
        select jsonb_object_agg(event_type, event_count)
        from (
          select event_type, count(*)::bigint as event_count
          from public.analytics_events
          where created_at >= now() - interval '30 days'
          group by event_type
        ) e
      ), '{}'::jsonb),
      'top_action_clubs', coalesce((
        select jsonb_agg(jsonb_build_object('club_slug', club_slug, 'actions', actions) order by actions desc)
        from (
          select club_slug, count(*)::bigint as actions
          from public.analytics_events
          where created_at >= now() - interval '30 days' and club_slug is not null
          group by club_slug
          order by count(*) desc
          limit 10
        ) c
      ), '[]'::jsonb),
      'top_pages', coalesce((
        select jsonb_agg(jsonb_build_object('path', path, 'views', views, 'visitors', visitors) order by views desc)
        from (
          select path, count(*)::bigint as views, count(distinct session_id)::bigint as visitors
          from public.page_views
          where created_at >= now() - interval '30 days'
          group by path
          order by count(*) desc
          limit 10
        ) t
      ), '[]'::jsonb),
      'top_sources', coalesce((
        select jsonb_agg(jsonb_build_object('source', source, 'views', views, 'visitors', visitors) order by views desc)
        from (
          select coalesce(nullif(referrer_host, ''), 'direct') as source, count(*)::bigint as views, count(distinct session_id)::bigint as visitors
          from public.page_views
          where created_at >= now() - interval '30 days'
          group by 1
          order by count(*) desc
          limit 10
        ) s
      ), '[]'::jsonb),
      'daily', coalesce((
        select jsonb_agg(jsonb_build_object('date', day::date, 'views', views, 'visitors', visitors) order by day)
        from (
          select date_trunc('day', created_at at time zone 'Asia/Baku') as day,
                 count(*)::bigint as views,
                 count(distinct session_id)::bigint as visitors
          from public.page_views
          where created_at >= now() - interval '14 days'
          group by 1
          order by 1
        ) d
      ), '[]'::jsonb)
    )
    else null
  end;
$$;

revoke all on function public.get_admin_analytics() from public, anon;
grant execute on function public.get_admin_analytics() to authenticated;
