create table if not exists public.engagement_events (
  id bigint generated by default as identity primary key,
  session_id text not null,
  event_type text not null,
  club_slug text not null,
  path text not null,
  created_at timestamptz not null default now(),
  constraint engagement_events_session_id_length check (char_length(session_id) between 8 and 64),
  constraint engagement_events_event_type check (event_type in ('maps_click','phone_click','instagram_click')),
  constraint engagement_events_club_slug check (club_slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$' and char_length(club_slug) <= 120),
  constraint engagement_events_path check (char_length(path) between 1 and 300 and path like '/klub/%')
);

create index if not exists idx_engagement_events_created_at on public.engagement_events (created_at desc);
create index if not exists idx_engagement_events_club_created_at on public.engagement_events (club_slug, created_at desc);
create index if not exists idx_engagement_events_type_created_at on public.engagement_events (event_type, created_at desc);

alter table public.engagement_events enable row level security;
revoke all on table public.engagement_events from anon, authenticated;
grant insert on table public.engagement_events to anon, authenticated;
grant select, delete on table public.engagement_events to authenticated;
grant usage, select on sequence public.engagement_events_id_seq to anon, authenticated;

create policy anon_insert_engagement_events on public.engagement_events
for insert to anon with check (
  char_length(session_id) between 8 and 64
  and event_type in ('maps_click','phone_click','instagram_click')
  and club_slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
  and path like '/klub/%'
);

create policy authenticated_insert_engagement_events on public.engagement_events
for insert to authenticated with check (
  char_length(session_id) between 8 and 64
  and event_type in ('maps_click','phone_click','instagram_click')
  and club_slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
  and path like '/klub/%'
);

create policy admin_read_engagement_events on public.engagement_events
for select to authenticated using (public.is_admin());
create policy admin_delete_engagement_events on public.engagement_events
for delete to authenticated using (public.is_admin());

create or replace function public.get_admin_analytics()
returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare result jsonb;
begin
  if not public.is_admin() then raise exception 'not authorized'; end if;

  select jsonb_build_object(
    'today_views', (select count(*) from public.page_views where created_at >= date_trunc('day', now() at time zone 'Asia/Baku') at time zone 'Asia/Baku'),
    'today_visitors', (select count(distinct session_id) from public.page_views where created_at >= date_trunc('day', now() at time zone 'Asia/Baku') at time zone 'Asia/Baku'),
    'views_7d', (select count(*) from public.page_views where created_at >= now() - interval '7 days'),
    'visitors_7d', (select count(distinct session_id) from public.page_views where created_at >= now() - interval '7 days'),
    'views_30d', (select count(*) from public.page_views where created_at >= now() - interval '30 days'),
    'visitors_30d', (select count(distinct session_id) from public.page_views where created_at >= now() - interval '30 days'),
    'top_pages', coalesce((select jsonb_agg(jsonb_build_object('path', path, 'views', views, 'visitors', visitors) order by views desc) from (select path, count(*)::bigint views, count(distinct session_id)::bigint visitors from public.page_views where created_at >= now()-interval '30 days' group by path order by count(*) desc limit 10) t), '[]'::jsonb),
    'top_sources', coalesce((select jsonb_agg(jsonb_build_object('source', source, 'views', views, 'visitors', visitors) order by views desc) from (select coalesce(nullif(lower(trim(referrer_host)),''),'direct') source, count(*)::bigint views, count(distinct session_id)::bigint visitors from public.page_views where created_at >= now()-interval '30 days' group by 1 order by count(*) desc limit 10) s), '[]'::jsonb),
    'daily', coalesce((select jsonb_agg(jsonb_build_object('date', day::date, 'views', views, 'visitors', visitors) order by day) from (select date_trunc('day', created_at at time zone 'Asia/Baku') day, count(*)::bigint views, count(distinct session_id)::bigint visitors from public.page_views where created_at >= now()-interval '14 days' group by 1 order by 1) d), '[]'::jsonb),
    'engagement_30d', coalesce((select jsonb_agg(jsonb_build_object('event_type', event_type, 'clicks', clicks, 'visitors', visitors) order by clicks desc) from (select event_type, count(*)::bigint clicks, count(distinct session_id)::bigint visitors from public.engagement_events where created_at >= now()-interval '30 days' group by event_type order by count(*) desc) e), '[]'::jsonb),
    'top_club_engagement', coalesce((select jsonb_agg(jsonb_build_object('club_slug', club_slug, 'clicks', clicks, 'visitors', visitors) order by clicks desc) from (select club_slug, count(*)::bigint clicks, count(distinct session_id)::bigint visitors from public.engagement_events where created_at >= now()-interval '30 days' group by club_slug order by count(*) desc limit 10) c), '[]'::jsonb)
  ) into result;
  return result;
end;
$$;

revoke all on function public.get_admin_analytics() from public, anon;
grant execute on function public.get_admin_analytics() to authenticated;
