create table if not exists public.page_views (
  id bigint generated by default as identity primary key,
  session_id text not null,
  path text not null,
  referrer_host text,
  created_at timestamptz not null default now(),
  constraint page_views_session_id_length check (char_length(session_id) between 8 and 64),
  constraint page_views_path_valid check (char_length(path) between 1 and 300 and path like '/%' and path not like '/admin%' and path not like '/api%'),
  constraint page_views_referrer_length check (referrer_host is null or char_length(referrer_host) <= 255)
);

create index if not exists idx_page_views_created_at on public.page_views (created_at desc);
create index if not exists idx_page_views_path_created_at on public.page_views (path, created_at desc);
create index if not exists idx_page_views_session_created_at on public.page_views (session_id, created_at desc);

alter table public.page_views enable row level security;

revoke all on table public.page_views from anon, authenticated;
grant insert on table public.page_views to anon, authenticated;
grant select, delete on table public.page_views to authenticated;
grant usage, select on sequence public.page_views_id_seq to anon, authenticated;

drop policy if exists anon_insert_page_views on public.page_views;
create policy anon_insert_page_views on public.page_views
  for insert to anon
  with check (
    char_length(session_id) between 8 and 64
    and char_length(path) between 1 and 300
    and path like '/%'
    and path not like '/admin%'
    and path not like '/api%'
  );

drop policy if exists authenticated_insert_page_views on public.page_views;
create policy authenticated_insert_page_views on public.page_views
  for insert to authenticated
  with check (
    char_length(session_id) between 8 and 64
    and char_length(path) between 1 and 300
    and path like '/%'
    and path not like '/admin%'
    and path not like '/api%'
  );

drop policy if exists admin_read_page_views on public.page_views;
create policy admin_read_page_views on public.page_views
  for select to authenticated
  using (public.is_admin());

drop policy if exists admin_delete_page_views on public.page_views;
create policy admin_delete_page_views on public.page_views
  for delete to authenticated
  using (public.is_admin());

create or replace function public.get_admin_analytics()
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  result jsonb;
begin
  if not public.is_admin() then
    raise exception 'not authorized';
  end if;

  select jsonb_build_object(
    'today_views', (select count(*) from public.page_views where created_at >= date_trunc('day', now() at time zone 'Asia/Baku') at time zone 'Asia/Baku'),
    'today_visitors', (select count(distinct session_id) from public.page_views where created_at >= date_trunc('day', now() at time zone 'Asia/Baku') at time zone 'Asia/Baku'),
    'views_7d', (select count(*) from public.page_views where created_at >= now() - interval '7 days'),
    'visitors_7d', (select count(distinct session_id) from public.page_views where created_at >= now() - interval '7 days'),
    'views_30d', (select count(*) from public.page_views where created_at >= now() - interval '30 days'),
    'visitors_30d', (select count(distinct session_id) from public.page_views where created_at >= now() - interval '30 days'),
    'top_pages', coalesce((
      select jsonb_agg(jsonb_build_object('path', path, 'views', views, 'visitors', visitors) order by views desc)
      from (
        select path, count(*)::bigint as views, count(distinct session_id)::bigint as visitors
        from public.page_views
        where created_at >= now() - interval '30 days'
        group by path
        order by count(*) desc
        limit 10
      ) t
    ), '[]'::jsonb),
    'daily', coalesce((
      select jsonb_agg(jsonb_build_object('date', day::date, 'views', views, 'visitors', visitors) order by day)
      from (
        select
          date_trunc('day', created_at at time zone 'Asia/Baku') as day,
          count(*)::bigint as views,
          count(distinct session_id)::bigint as visitors
        from public.page_views
        where created_at >= now() - interval '14 days'
        group by 1
        order by 1
      ) d
    ), '[]'::jsonb)
  ) into result;

  return result;
end;
$$;

revoke all on function public.get_admin_analytics() from public, anon;
grant execute on function public.get_admin_analytics() to authenticated;
